version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:80"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DBp@ssw0rd
    ports:
      - "1433:1433"
