name: Terraform Deploy to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Adjust based on your Terraform version

    # Authenticate with Azure
    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Initialize Terraform
    - name: Set Environment Variables for Azure Authentication
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
        export ARM_CLIENT_ID=$AZURE_CLIENT_ID
        export ARM_CLIENT_SECRET=$AZURE_CLIENT_SECRET
        export ARM_TENANT_ID=$AZURE_TENANT_ID
        export ARM_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    
    # - name: Terraform Init
    #   run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve

    # Plan Terraform changes
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Apply Terraform changes
    - name: Terraform Apply
      if: github.event_name == 'push' # Only auto-apply on pushes
      run: terraform apply -auto-approve tfplan
